
colnames = ['RefId', 'IsBadBuy', 'PurchDate', 'Auction', 'VehYear', 'VehicleAge', 'Make',  'Model', 'Trim',  'SubModel', 'Color', 'Transmission', 'WheelTypeID', 'WheelType', 'VehOdo', 'Nationality', 'Size',  'TopThreeAmericanName', 'MMRAcquisitionAuctionAveragePrice', 'MMRAcquisitionAuctionCleanPrice', 'MMRAcquisitionRetailAveragePrice', 'MMRAcquisitonRetailCleanPrice', 'MMRCurrentAuctionAveragePrice', 'MMRCurrentAuctionCleanPrice', 'MMRCurrentRetailAveragePrice', 'MMRCurrentRetailCleanPrice', 'PRIMEUNIT', 'AUCGUART', 'BYRNO', 'VNZIP1', 'VNST',  'VehBCost', 'IsOnlineSale', 'WarrantyCost']

datatypes = [
        ('RefId', 'int32'),
        ('IsBadBuy', 'i1'),
        ('PurchDate', 'int64'),
        ('Auction', 'S10'),
        ('VehYear', 'int64'),
        ('VehicleAge', 'int32'),
        ('Make', 'S10'),
        ('Model', 'S10'),
        ('Trim', 'S10'),
        ('SubModel', 'S10'),
        ('Color', 'S10'),
        ('Transmission', 'S10'),
        ('WheelTypeID', 'int32'),
        ('WheelType', 'S10'),
        ('VehOdo', 'int32'),
        ('Nationality', 'S10'),
        ('Size', 'S10'),
        ('TopThreeAmericanName', 'S10'),
        ('MMRAcquisitionAuctionAveragePrice', 'int32'),
        ('MMRAcquisitionAuctionCleanPrice', 'int32'),
        ('MMRAcquisitionRetailAveragePrice', 'int32'),
        ('MMRAcquisitonRetailCleanPrice', 'int32'),
        ('MMRCurrentAuctionAveragePrice', 'int32'),
        ('MMRCurrentAuctionCleanPrice', 'int32'),
        ('MMRCurrentRetailAveragePrice', 'int32'),
        ('MMRCurrentRetailCleanPrice', 'int32'),
        ('PRIMEUNIT', 'S10'),
        ('AUCGUART', 'S10'),
        ('BYRNO', 'int32'),
        ('VNZIP1', 'int32'),
        ('VNST', 'S10'),
        ('VehBCost', 'int32'),
        ('IsOnlineSale', 'S10'),
        ('WarrantyCost', 'int32')
    ]